export const settingsPreferences = {
    languages: [
      { code: "en-UK", label: "English" },
      { code: "pl", label: "Polski" },
      { code: "es", label: "Español" },
      { code: "fr", label: "Français" },
      { code: "de", label: "Deutsch" }
    ],
    timezones: [
      { code: "GMT-12", label: "(GMT-12:00) International Date Line West" },
      { code: "GMT-11", label: "(GMT-11:00) Midway Island, Samoa" },
      { code: "GMT-10", label: "(GMT-10:00) Hawaii" },
      { code: "GMT-9", label: "(GMT-09:00) Alaska" },
      { code: "GMT-8", label: "(GMT-08:00) Pacific Time (US & Canada)" },
      { code: "GMT-7", label: "(GMT-07:00) Mountain Time (US & Canada)" },
      { code: "GMT-6", label: "(GMT-06:00) Central Time (US & Canada)" },
      { code: "GMT-5", label: "(GMT-05:00) Eastern Time (US & Canada)" },
      { code: "GMT-4", label: "(GMT-04:00) Atlantic Time (Canada)" },
      { code: "GMT-3", label: "(GMT-03:00) Buenos Aires, Georgetown" },
      { code: "GMT-2", label: "(GMT-02:00) Mid-Atlantic" },
      { code: "GMT-1", label: "(GMT-01:00) Azores, Cape Verde Islands" },
      { code: "GMT", label: "(GMT+00:00) London, Lisbon, Casablanca" },
      { code: "GMT+1", label: "(GMT+01:00) Warsaw, Berlin, Paris" },
      { code: "GMT+2", label: "(GMT+02:00) Athens, Cairo, Jerusalem" },
      { code: "GMT+3", label: "(GMT+03:00) Moscow, Riyadh, Nairobi" },
      { code: "GMT+4", label: "(GMT+04:00) Dubai, Abu Dhabi, Muscat" },
      { code: "GMT+5", label: "(GMT+05:00) Islamabad, Karachi, Tashkent" },
      { code: "GMT+6", label: "(GMT+06:00) Almaty, Dhaka, Novosibirsk" },
      { code: "GMT+7", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
      { code: "GMT+8", label: "(GMT+08:00) Beijing, Singapore, Perth" },
      { code: "GMT+9", label: "(GMT+09:00) Tokyo, Seoul, Osaka" },
      { code: "GMT+10", label: "(GMT+10:00) Sydney, Brisbane, Vladivostok" },
      { code: "GMT+11", label: "(GMT+11:00) Magadan, Solomon Islands" },
      { code: "GMT+12", label: "(GMT+12:00) Auckland, Fiji" }
    ],
    reminderTimes: [
      { value: "06:00", label: "6 AM" },
      { value: "07:00", label: "7 AM" },
      { value: "08:00", label: "8 AM" },
      { value: "09:00", label: "9 AM" },
      { value: "10:00", label: "10 AM" },
      { value: "11:00", label: "11 AM" },
      { value: "12:00", label: "12 PM (Noon)" },
      { value: "13:00", label: "1 PM" },
      { value: "14:00", label: "2 PM" },
      { value: "15:00", label: "3 PM" },
      { value: "16:00", label: "4 PM" },
      { value: "17:00", label: "5 PM" },
      { value: "18:00", label: "6 PM" },
      { value: "19:00", label: "7 PM" },
      { value: "20:00", label: "8 PM" },
      { value: "21:00", label: "9 PM" },
      { value: "22:00", label: "10 PM" }
    ]
  };
